<?php

namespace Cacko\Yii2\Widgets\MonacoEditor;

use Cacko\Yii2\Widgets\MonacoEditor\models\EditorOptions;
use Yii;
use yii\base\ViewContextInterface;
use yii\base\Widget;
use yii\helpers\Json;
use yii\web\AssetBundle;

class EditorAsset extends AssetBundle
{

    const PLUGIN_NAME = 'monacoEditor';

    public $sourcePath = __DIR__ . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR;

    public $js = [
        'js/jquery-monaco-editor.js'
    ];

    public $css = [
        'css/monaco-icons.css',
        'css/monaco-widget.scss',
    ];

    public $depends = [
        'yii\web\YiiAsset',
        'Cacko\Yii2\Widgets\MonacoEditor\MonacoEditorAsset'
    ];

    public static function register($view)
    {
        $options = Yii::createObject(EditorOptions::class);
        $view->registerJs(';$.fn.' . static::PLUGIN_NAME . '.defaults = ' . Json::encode($options) . ';');
        return parent::register($view);
    }


    public static function registerWidget(ViewContextInterface $widget, EditorOptions $options): AssetBundle
    {

        /** @var Widget $widget */
        $view = $widget->view;

        $widgetId = $widget->id;
        $options = Json::encode($options);

        $bundle = static::register($view); // TODO: Change the autogenerated stub
        $view->registerJs(sprintf("$('#%s').%s(%s);", $widgetId, static::PLUGIN_NAME, $options));

        return $bundle;
    }
}
