<?php

namespace Cacko\Yii2\Widgets\MonacoEditor;

use yii\base\ViewContextInterface;
use yii\base\Widget;
use yii\helpers\Json;
use yii\web\AssetBundle;

class EditorAsset extends AssetBundle
{

    public $sourcePath = __DIR__ . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR;

    public $js = [
        'js/jquery-monaco-editor.js'
    ];

    public $css = [
        'css/monaco-icons.css',
        'css/monaco-widget.scss',
    ];

    public $depends = [
        'yii\web\YiiAsset',
        'Cacko\Yii2\Widgets\MonacoEditor\MonacoEditorAsset'
    ];
    /**
     * @param ViewContextInterface $widget
     * @param array $options
     * @return AssetBundle
     * @throws \ReflectionException
     */
    public static function registerWidget(ViewContextInterface $widget, $options = []): AssetBundle
    {

        /** @var Widget $widget */
        $view = $widget->view;

        $widgetId = $widget->id;
        $options = Json::encode($options);

        $assetName = (new \ReflectionClass(get_called_class()))->getShortName();
        $pluginName = str_replace('Asset', '', $assetName);

        $bundle = static::register($view); // TODO: Change the autogenerated stub
        $view->registerJs(sprintf("$('#%s').monaco%s(%s);", $widgetId, $pluginName, $options));

        return $bundle;
    }
}
